# Generated by Django 4.0.4 on 2022-05-28 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hiring', '0013_alter_applicant_apl_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.TextField(null=True)),
                ('task_status', models.CharField(choices=[('BACKLOG', 'BACKLOG'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE'), ('TESTED', 'TESTED'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], default='BACKLOG', max_length=20)),
                ('task_created_on', models.DateTimeField(auto_now_add=True)),
                ('task_updated_on', models.DateTimeField(auto_now=True)),
                ('task_start_date', models.DateTimeField(null=True)),
                ('task_end_date', models.DateTimeField(null=True)),
                ('task_estimated_time', models.IntegerField(null=True)),
                ('task_actual_time', models.IntegerField(null=True)),
                ('task_priority', models.IntegerField(null=True)),
                ('task_assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_by', to='hiring.employee')),
                ('task_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_to', to='hiring.employee')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('task_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_review_rating', models.IntegerField(null=True)),
                ('task_review_comment', models.TextField(null=True)),
                ('task_review_created_on', models.DateTimeField(auto_now_add=True)),
                ('task_review_updated_on', models.DateTimeField(auto_now=True)),
                ('task_review_type', models.CharField(choices=[('ANONYMOUS', 'ANONYMOUS'), ('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC')], default='PUBLIC', max_length=20)),
                ('task_review_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_review_emp_id', to='hiring.employee')),
                ('task_review_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'db_table': 'task_review',
            },
        ),
        migrations.CreateModel(
            name='RewardCoins',
            fields=[
                ('reward_coins_id', models.AutoField(primary_key=True, serialize=False)),
                ('reward_coins_points', models.IntegerField()),
                ('reward_coins_created_on', models.DateTimeField(auto_now_add=True)),
                ('reward_coins_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_coins_emp_id', to='hiring.employee')),
            ],
            options={
                'db_table': 'reward_coins',
            },
        ),
    ]
