# Generated by Django 4.0.4 on 2022-05-28 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0013_alter_applicant_apl_email'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_by', to='hiring.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_to', to='hiring.employee'),
        ),
    ]
