# Generated by Django 4.0.4 on 2022-05-26 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('apl_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('apl_details_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('apl_id', models.AutoField(primary_key=True, serialize=False)),
                ('apl_name', models.CharField(max_length=100)),
                ('apl_email', models.EmailField(max_length=100)),
                ('apl_phone', models.CharField(max_length=20)),
                ('apl_joined', models.DateTimeField(auto_now_add=True)),
                ('apl_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.applicantdetails')),
            ],
        ),
    ]
