# Generated by Django 4.0.4 on 2022-05-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicant',
            table='applicant',
        ),
        migrations.AlterModelTable(
            name='applicantdetails',
            table='applicant_details',
        ),
    ]
