# Generated by Django 4.0.4 on 2022-05-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_alter_applicant_table_alter_applicantdetails_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='apl_details',
        ),
        migrations.AddField(
            model_name='applicantdetails',
            name='apl_details_apl_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hiring.applicant'),
            preserve_default=False,
        ),
    ]
