# Generated by Django 4.0.4 on 2022-05-27 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_remove_applicant_apl_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=100)),
                ('emp_phone', models.CharField(max_length=20)),
                ('emp_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='apl_details_address',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='EmployeePersonalDetails',
            fields=[
                ('emp_personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_personal_address', models.CharField(max_length=500)),
                ('emp_personal_education', models.CharField(max_length=500)),
                ('emp_personal_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.employee')),
            ],
            options={
                'db_table': 'employee_personal_details',
            },
        ),
        migrations.CreateModel(
            name='EmployeeJobDetails',
            fields=[
                ('emp_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_job_department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('ACCOUNT', 'ACCOUNT'), ('SALES', 'SALES'), ('MARKETING', 'MARKETING'), ('FINANCE', 'FINANCE'), ('ADMIN', 'ADMIN'), ('OTHER', 'OTHER')], default='IT', max_length=100)),
                ('emp_job_designation', models.CharField(choices=[('SDE1', 'SDE1'), ('SDE2', 'SDE2'), ('SDE3', 'SDE3'), ('SENIOR_SDE', 'SENIOR_SDE'), ('MANAGER', 'MANAGER'), ('DIRECTOR', 'DIRECTOR'), ('OTHER', 'OTHER')], default='SDE1', max_length=100)),
                ('emp_job_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.employee')),
                ('emp_job_reporting_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_to', to='hiring.employee')),
            ],
            options={
                'db_table': 'employee_job_details',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAssetRegistry',
            fields=[
                ('emp_asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_asset_name', models.CharField(max_length=100)),
                ('emp_asset_description', models.CharField(max_length=500)),
                ('emp_asset_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.employee')),
            ],
            options={
                'db_table': 'employee_asset_registry',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccountingDetails',
            fields=[
                ('emp_accounting_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_accounting_salary', models.IntegerField()),
                ('emp_accounting_number', models.CharField(max_length=20)),
                ('emp_accounting_pf', models.CharField(max_length=20)),
                ('emp_accounting_uan', models.CharField(max_length=20)),
                ('emp_accounting_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.employee')),
            ],
            options={
                'db_table': 'employee_accounting_details',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.role'),
        ),
    ]
