# Generated by Django 4.0.4 on 2022-05-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_employee_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('job_app_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_app_title', models.CharField(max_length=100)),
                ('job_app_description', models.CharField(max_length=500)),
                ('job_app_location', models.CharField(max_length=100)),
                ('job_app_salary', models.IntegerField()),
                ('job_app_created', models.DateTimeField(auto_now_add=True)),
                ('job_app_type', models.CharField(choices=[('ENGINEERING', 'ENGINEERING'), ('ACCOUNTS', 'ACCOUNTS'), ('BUSINESS-AFFAIRS', 'BUSINESS-AFFAIRS'), ('SALES', 'SALES'), ('MARKETING', 'MARKETING'), ('DESIGN', 'DESIGN'), ('OTHER', 'OTHER')], default='ENGINEERING', max_length=100)),
                ('job_app_hr_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.employee')),
                ('job_app_manager_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_id', to='hiring.employee')),
            ],
            options={
                'db_table': 'job_application',
            },
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_appl_status', models.CharField(max_length=100)),
                ('job_apl_scheduled_time', models.DateTimeField(null=True)),
                ('job_appl_created', models.DateTimeField(auto_now_add=True)),
                ('job_appl_apl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.applicant')),
                ('job_appl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.jobapplication')),
            ],
            options={
                'db_table': 'job_applicant',
            },
        ),
    ]
