# Generated by Django 4.0.4 on 2022-05-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0005_jobapplication_jobapplicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicant',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='job_appl_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
