# Generated by Django 4.0.4 on 2022-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0007_jobapplicant_job_appl_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='apl_linkedin',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
