# Generated by Django 4.0.4 on 2022-05-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0008_applicant_apl_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='apl_linkedin',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
