# Generated by Django 4.0.4 on 2022-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0009_alter_applicant_apl_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_sub_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='job_appl_status',
            field=models.CharField(choices=[('APPLIED', 'APPLIED'), ('ACCEPTED', 'ACCEPTED'), ('SCHEDULED', 'SCHEDULED'), ('INTERVIEWED', 'INTERVIEWED'), ('SELECTED', 'SELECTED'), ('REJECTED', 'REJECTED')], default='APPLIED', max_length=100),
        ),
    ]
