# Generated by Django 4.0.4 on 2022-05-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0010_jobapplication_job_sub_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_sub_title',
            new_name='job_app_sub_title',
        ),
    ]
