# Generated by Django 4.0.4 on 2022-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0012_alter_employee_emp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='apl_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
